/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The well currently being drilled (sidebar card, page header chip, hero blocks) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active well */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActiveWell"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{wellId}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Command Centre aggregate — hero, 4 primary metrics, 8 extra params, top risk, summary bar */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wellId: components["parameters"]["wellId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard bundle */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dashboard"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{wellId}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest eRTMAC snapshot (primary + more parameters, sparklines) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wellId: components["parameters"]["wellId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Live snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LiveSnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws/wells/{wellId}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket: pushes a LiveSnapshot every ~2 s, plus alert messages when an alert fires
         * @description Upgrade to WebSocket. Messages are JSON objects of the form {"type": "live" | "alert" | "risk", "data": {...}}.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wellId: components["parameters"]["wellId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching protocols */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{wellId}/offsets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nearby Wells — offsets within a radius, measured at bit depth */
        get: {
            parameters: {
                query?: {
                    radius_km?: 1 | 3 | 5 | 10;
                    min_similarity?: number;
                    has_loss_events?: boolean;
                    sort?: "distance" | "similarity";
                };
                header?: never;
                path: {
                    wellId: components["parameters"]["wellId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Offsets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            radiusKm?: number;
                            count?: number;
                            relevantCount?: number;
                            wells?: components["schemas"]["OffsetWell"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{wellId}/offsets/{offsetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One offset well with its key events (Nearby Wells drawer) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wellId: components["parameters"]["wellId"];
                    offsetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Offset detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OffsetWell"] & {
                            events?: components["schemas"]["Event"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{wellId}/corridor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Well depth corridor — formation bands and events per well, aligned by MD, TVDSS or formation */
        get: {
            parameters: {
                query?: {
                    align?: "md" | "tvdss" | "formation";
                    look_ahead_m?: number;
                    top_m?: number;
                    span_m?: number;
                };
                header?: never;
                path: {
                    wellId: components["parameters"]["wellId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Corridor columns */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Corridor"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{wellId}/compare/{offsetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Well Comparison — parameters at the same formation-relative depth, design, events, takeaway */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wellId: components["parameters"]["wellId"];
                    offsetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Comparison */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comparison"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{wellId}/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk Centre matrix — all hazards ahead of the bit */
        get: {
            parameters: {
                query?: {
                    level?: "HIGH" | "MEDIUM" | "LOW";
                };
                header?: never;
                path: {
                    wellId: components["parameters"]["wellId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Risks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            counts?: {
                                HIGH?: number;
                                MEDIUM?: number;
                                LOW?: number;
                            };
                            nextZone?: Record<string, never>;
                            risks?: components["schemas"]["RiskSummary"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{wellId}/risks/{riskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence drawer — why this risk, historical evidence, mitigations, recommendation, model details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    wellId: components["parameters"]["wellId"];
                    riskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Risk detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RiskDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{wellId}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alert timeline for today */
        get: {
            parameters: {
                query?: {
                    status?: "all" | "open" | "acknowledged";
                };
                header?: never;
                path: {
                    wellId: components["parameters"]["wellId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alerts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            counts?: {
                                all?: number;
                                open?: number;
                                acknowledged?: number;
                            };
                            alerts?: components["schemas"]["Alert"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alertId}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge an alert */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    alertId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        by?: string;
                    };
                };
            };
            responses: {
                /** @description Updated alert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
            };
        };
        /** Undo acknowledgement */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    alertId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated alert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Knowledge Centre search over extracted events */
        get: {
            parameters: {
                query?: {
                    /** @description Free text (hybrid keyword + vector search) */
                    q?: string;
                    preset?: "loss_near_barail" | "stuck_in_barail" | "kick" | "cementing" | "similar_to_active";
                    well?: string;
                    formation?: string;
                    type?: "LOSS" | "STUCK" | "KICK" | "CEMENT" | "TORQUE" | "OTHER";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Events sorted by aligned depth on the active well */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            count?: number;
                            presets?: {
                                id?: string;
                                label?: string;
                                count?: number;
                            }[];
                            events?: components["schemas"]["Event"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One event with cause, action, outcome, lost time and source page */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Event"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/neighbourhood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Knowledge Graph — n-hop neighbourhood with the evidence path */
        get: {
            parameters: {
                query?: {
                    node?: string;
                    hops?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Graph */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Graph"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document library */
        get: {
            parameters: {
                query?: {
                    type?: "WCR" | "DDR" | "MUD LOG" | "SURVEY";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Documents and totals */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            totals?: Record<string, never>;
                            documents?: components["schemas"]["Document"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Upload a WCR, DDR, log or survey — starts an OCR → NLP → graph job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                        wellId?: string;
                        /** @enum {string} */
                        type?: "WCR" | "DDR" | "MUD LOG" | "SURVEY" | "OTHER";
                    };
                };
            };
            responses: {
                /** @description Job queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Processing jobs with per-stage progress */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Jobs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{documentId}/pages/{page}/extraction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Intelligence — pipeline state, page text/lines and extracted fields with confidence and boxes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documentId: string;
                    page: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Extraction */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Extraction"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/extractions/fields/{fieldId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit an extracted value (human review) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fieldId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        value?: string;
                    };
                };
            };
            responses: {
                /** @description Updated field */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/extractions/fields/{fieldId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a low-confidence field; when all fields pass, the event is written to the graph */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fieldId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated extraction (pipeline advances to GRAPH) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The six Analytics charts */
        get: {
            parameters: {
                query?: {
                    well?: string;
                    radius_km?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Chart data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask NWIS — returns a structured, cited answer or a refusal when nothing supports it */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        question: string;
                        context?: {
                            wellId?: string;
                            depthMdM?: number;
                            radiusKm?: number;
                        };
                    };
                };
            };
            responses: {
                /** @description Answer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Answer"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quick-question chips and the context panel */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Suggestions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActiveWell: {
            id?: string;
            /** @enum {string} */
            status?: "DRILLING" | "TRIPPING" | "CIRCULATING" | "CASING" | "CEMENTING" | "SUSPENDED";
            rigState?: string;
            holeSection?: string;
            bit?: {
                mdM?: number;
                tvdssM?: number;
            };
            currentFormation?: string;
            nextFormation?: {
                name?: string;
                topMdM?: number;
                topTvdssM?: number;
                uncertaintyM?: number;
                distanceM?: number;
                etaHours?: number;
            };
            lookAheadM?: number;
        };
        Metric: {
            key?: string;
            label?: string;
            value?: number;
            unit?: string;
            note?: string;
            /** @enum {string} */
            status?: "NORMAL" | "WATCH" | "ALARM";
        };
        LiveSnapshot: {
            wellId?: string;
            timestamp?: string;
            source?: string;
            primary?: components["schemas"]["Metric"][];
            more?: components["schemas"]["Metric"][];
        };
        Dashboard: {
            activeWell?: components["schemas"]["ActiveWell"];
            live?: components["schemas"]["LiveSnapshot"];
            topRisk?: Record<string, never>;
            mapWells?: components["schemas"]["OffsetWell"][];
            summary?: Record<string, never>;
        };
        OffsetWell: {
            id?: string;
            /** @description [east, north] from the active surface location */
            surfaceKm?: number[];
            /** @description position at the active bit depth */
            bitDepthKm?: number[];
            distanceAtBitKm?: number;
            similarity?: number;
            similarityFactors?: {
                stratigraphy?: number;
                trajectory?: number;
                mudSystem?: number;
                proximity?: number;
            };
            relevant?: boolean;
            tdMdM?: number;
            barailTopTvdssM?: number;
            spud?: number;
            status?: string;
            /** @enum {string} */
            risk?: "HIGH" | "MEDIUM" | "LOW";
            hasLossEvents?: boolean;
        };
        Event: {
            id?: string;
            wellId?: string;
            /** @enum {string} */
            type?: "LOSS" | "STUCK" | "KICK" | "CEMENT" | "TORQUE" | "OTHER";
            title?: string;
            /** @enum {string} */
            severity?: "high" | "med" | "low";
            formation?: string;
            mdM?: number;
            tvdssM?: number | null;
            metresBelowBarailTop?: number | null;
            alignedMdOnActiveM?: number | null;
            date?: string;
            cause?: string;
            action?: string;
            outcome?: string;
            nptHours?: number;
            extractionConfidence?: number;
            source?: {
                type?: string;
                documentId?: string;
                page?: number | null;
                label?: string;
            };
        };
        Corridor: {
            align?: string;
            axis?: {
                topM?: number;
                spanM?: number;
                unit?: string;
            };
            bit?: {
                depthM?: number;
                lookAheadM?: number;
            };
            caption?: string;
            columns?: {
                wellId?: string;
                distanceKm?: number;
                shiftM?: number;
                bands?: {
                    name?: string;
                    fromM?: number;
                    toM?: number;
                }[];
                events?: {
                    eventId?: string;
                    depthM?: number;
                    inLookAhead?: boolean;
                    type?: string;
                    severity?: string;
                    label?: string;
                }[];
            }[];
        };
        Comparison: {
            active?: string;
            offset?: components["schemas"]["OffsetWell"];
            parameters?: {
                key?: string;
                label?: string;
                unit?: string;
                active?: number;
                offset?: number;
                diffPct?: number;
                /** @description |diff| > 8 % */
                flagged?: boolean;
            }[];
            design?: {
                label?: string;
                active?: string;
                offset?: string;
                differs?: boolean;
            }[];
            events?: components["schemas"]["Event"][];
            takeaway?: {
                text?: string;
                source?: string;
            };
        };
        RiskSummary: {
            id?: string;
            name?: string;
            probability?: number;
            /** @enum {string} */
            level?: "HIGH" | "MEDIUM" | "LOW";
            windowMdM?: number[];
            confidence?: number;
            confidenceBand?: string;
            evidenceSummary?: string;
            /** @enum {string} */
            status?: "ACT_NOW" | "WATCH" | "MONITOR";
        };
        RiskDetail: components["schemas"]["RiskSummary"] & {
            stats?: {
                value?: string;
                label?: string;
            }[];
            reasons?: string[];
            evidence?: components["schemas"]["Event"][];
            mitigations?: {
                text?: string;
                worked?: boolean;
            }[];
            recommendation?: string;
            model?: Record<string, never>;
        };
        Alert: {
            id?: string;
            time?: string;
            /** @enum {string} */
            severity?: "HIGH" | "WATCH" | "MEDIUM" | "INFO";
            category?: string;
            riskId?: string | null;
            title?: string;
            subtitle?: string;
            acknowledged?: {
                by?: string;
                at?: string;
            } | null;
            triggers?: {
                value?: string;
                label?: string;
            }[];
            chart?: {
                label?: string;
                series?: number[];
                limit?: number | null;
            };
            offsetsSay?: string;
            action?: string;
        };
        Document: {
            id?: string;
            wellId?: string;
            type?: string;
            year?: number;
            pages?: number;
            events?: number;
            ocrQuality?: number;
            /** @enum {string} */
            status?: "VERIFIED" | "INDEXED" | "PROCESSING" | "NEEDS_REVIEW" | "QUEUED" | "FAILED";
        };
        Job: {
            id?: string;
            documentId?: string;
            description?: string;
            stages?: {
                ocr?: number;
                nlp?: number;
                graph?: number;
            };
            /** @enum {string} */
            state?: "QUEUED" | "RUNNING" | "DONE" | "FAILED";
        };
        Extraction: {
            documentId?: string;
            page?: number;
            reviewThreshold?: number;
            pipeline?: {
                step?: string;
                detail?: string;
                /** @enum {string} */
                state?: "DONE" | "CURRENT" | "PENDING";
            }[];
            pageText?: string[];
            event?: {
                eventId?: string;
                fields?: {
                    id?: string;
                    key?: string;
                    label?: string;
                    value?: string;
                    confidence?: number;
                    needsReview?: boolean;
                    /** @description Page coordinates of the source text (x, y, w, h in PDF points in the real system) */
                    bbox?: Record<string, never>;
                }[];
            };
        };
        Graph: {
            nodes?: {
                id?: string;
                label?: string;
                /** @enum {string} */
                type?: "active_well" | "well" | "formation" | "event" | "cause" | "action" | "outcome" | "document";
                severity?: string;
                ref?: string;
            }[];
            edges?: {
                id?: string;
                from?: string;
                to?: string;
                relation?: string;
                label?: string;
            }[];
            evidencePath?: string[];
        };
        Answer: {
            question?: string;
            answer?: string;
            refused?: boolean;
            evidence?: {
                text?: string;
                source?: string;
                severity?: string;
            }[];
            similarWells?: {
                id?: string;
                similarity?: number;
            }[];
            sources?: string[];
            confidence?: {
                score?: number;
                band?: string;
                note?: string;
            };
            cta?: {
                label?: string;
                route?: string;
            };
            meta?: Record<string, never>;
        };
    };
    responses: never;
    parameters: {
        wellId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
