/**
 * Projection test: the API's kilometre offsets must land where the demo file says they do.
 *
 * The API carries no absolute position. It returns `surfaceKm` and `bitDepthKm` — kilometre offsets
 * from a local origin — and every absolute coordinate in the app is derived from them by
 * `kmToLngLat`. That makes the projection load-bearing: if it is wrong, nothing is misplaced by a
 * little, the entire field is in the wrong place, and nothing in the type system or the render
 * would say so. `public/data/wellfield-demo.geojson` carries the same ten wells with both absolute
 * positions already projected, so it pins the answer.
 *
 * Two things this is worth being precise about, because a test that blurs them is worse than none:
 *
 *  1. **This is a regression lock, not an independent survey.** The fixture was generated by this
 *     same `kmToLngLat` at this same origin, so the errors below are round-off, not the difference
 *     between the projection and the real world. It will catch a wrong origin, a flipped axis, a
 *     dropped `cos(lat)`, or a unit slip — which are the failures that actually happen. It will not
 *     catch a systematically wrong constant, because the wrong constant would be in both sides.
 *
 *  2. **The longitude scale uses `cos` of the origin's latitude, not of each point's latitude.**
 *     That is the specified model: a tangent plane anchored at one parallel, so the east-west scale
 *     is constant across the field. It is not a per-point equirectangular projection. Over the
 *     demo field's ±5 km the two differ by well under a metre, and the constant-cosine form is what
 *     the brief fixes, so that is what is tested — but the approximation is real and the tolerance
 *     below is measured against the fixture, not against WGS84.
 *
 * Node strips the TypeScript types natively, so this imports the module the app ships rather than a
 * transcription of it. A test that reimplemented the formula would pass while the app was broken.
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { ORIGIN, kmToLngLat, lngLatToKm } from './src/lib/geo.ts'

const TOLERANCE_M = 1
const FIXTURE = new URL('./public/data/wellfield-demo.geojson', import.meta.url)

/** Great-circle distance in metres. Haversine, so it is not a test of the same maths it checks. */
function metresBetween(a, b) {
  const R = 6371008.8
  const toRad = (d) => (d * Math.PI) / 180
  const dLat = toRad(b[1] - a[1])
  const dLng = toRad(b[0] - a[0])
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(a[1])) * Math.cos(toRad(b[1])) * Math.sin(dLng / 2) ** 2
  return 2 * R * Math.asin(Math.min(1, Math.sqrt(h)))
}

let failures = 0
const fail = (msg) => {
  failures += 1
  console.log(`  FAIL ${msg}`)
}

const gj = JSON.parse(readFileSync(FIXTURE, 'utf8'))
console.log(`geo projection vs ${FIXTURE.pathname.split('/').slice(-2).join('/')}`)
console.log(`  origin ${ORIGIN.lng}, ${ORIGIN.lat}   tolerance ${TOLERANCE_M} m\n`)

let worst = { m: 0, where: '' }
for (const f of gj.features) {
  const p = f.properties
  // The API calls the bit offset `bitDepthKm`; the fixture calls it `bitKm`. Same field.
  for (const [kmKey, absKey] of [
    ['surfaceKm', 'surface'],
    ['bitKm', 'bit'],
  ]) {
    const km = p[kmKey]
    const expected = p[absKey]
    if (!Array.isArray(km) || !Array.isArray(expected)) {
      fail(`${p.id}: missing ${kmKey} or ${absKey} in the fixture`)
      continue
    }
    const got = kmToLngLat(km)
    const m = metresBetween(got, expected)
    if (m > worst.m) worst = { m, where: `${p.id} ${absKey}` }
    if (m > TOLERANCE_M) {
      fail(
        `${p.id} ${absKey}: ${km} km → [${got[0].toFixed(6)}, ${got[1].toFixed(6)}], ` +
          `fixture [${expected[0].toFixed(6)}, ${expected[1].toFixed(6)}] — off by ${m.toFixed(3)} m`,
      )
    }
    // The inverse has to close too, or a readout that converts the camera position back to km
    // (MapCanvas) drifts from the projection that placed the layer.
    const back = lngLatToKm(got)
    const drift = Math.hypot(back[0] - km[0], back[1] - km[1]) * 1000
    if (drift > 1e-6) fail(`${p.id} ${absKey}: inverse drift ${drift.toExponential(2)} m`)
  }
}

console.log(
  `  ${gj.features.length} wells x 2 points = ${gj.features.length * 2} projections checked` +
    `, worst ${worst.m.toExponential(2)} m (${worst.where})`,
)

if (failures) {
  console.log(`\n${failures} projection failure(s)`)
  process.exit(1)
}
console.log('  ok  every surface and bit point projects onto the fixture within 1 m')
