import type { LandAreaPreset } from "./types";

export const LAND_AREAS: LandAreaPreset[] = [
  {
    id: "duliajan-basin",
    name: "Duliajan Oil Field (Upper Assam Basin)",
    basin: "Upper Assam Shelf",
    centerLat: 27.34,
    centerLng: 95.32,
    defaultRadiusKm: 10,
    faultLines: [
      {
        name: "North Fault System",
        type: "Major Normal Fault (Regional Extensional)",
        coords: [
          { lat: 27.385, lng: 95.27 },
          { lat: 27.37, lng: 95.305 },
          { lat: 27.355, lng: 95.345 },
          { lat: 27.348, lng: 95.385 },
        ],
      },
      {
        name: "Flank Thrust Zone",
        type: "Compressional Thrust Fault",
        coords: [
          { lat: 27.315, lng: 95.28 },
          { lat: 27.31, lng: 95.325 },
          { lat: 27.302, lng: 95.37 },
        ],
      },
    ],
    highRiskZones: [
      {
        name: "Disang High Loss Corridor",
        riskType: "Severe Mud Loss & Fracture Vug",
        centerLat: 27.348,
        centerLng: 95.312,
        radiusKm: 2.2,
      },
      {
        name: "North Fault Shear & Overpressure Bubble",
        riskType: "Gas Kick & Dynamic Overpressure (1.28 SG Eq.)",
        centerLat: 27.362,
        centerLng: 95.342,
        radiusKm: 1.8,
      },
    ],
    potentialWells: [
      {
        id: "DJN-301",
        name: "DJN-301 (Planned Development)",
        code: "DJN-301",
        field: "Duliajan Field",
        basin: "Upper Assam Basin",
        targetFormation: "Disang Formation & Tipam Sandstone",
        wellType: "Development",
        targetTdMd: 3500,
        targetTvd: 3320,
        surfaceLat: 27.34,
        surfaceLng: 95.32,
        surfaceUtmX: 432850,
        surfaceUtmY: 3024600,
        crs: "WGS 84 / UTM Zone 46N (EPSG:32646)",
        searchRadiusKm: 10,
        geologicalJustification: {
          targetStructure: "South Flank Anticlinal Dome with structural four-way dipping closure",
          structuralClosure: "420 meters vertical closure bounded north by the North Fault system",
          faultSealingIntegrity: "High clay smear factor (0.78) ensuring fault trap hermetic seal",
          reservoirQualityIndex: "0.84 (P10 net pay estimate: 34.2 m across Tipam and Upper Disang)",
          permeabilityPorosityEst: "Porosity: 19.5% - 23.0%, Permeability: 140 - 320 mD",
          scientificRationale:
            "Analogue drainage analysis from offset wells DJN-178 and DJN-181 demonstrates unswept oil accumulation in fault block 4B. The trajectory optimizes reservoir penetration while maintaining safe stand-off from the high-risk North Fault shear zone.",
          expectedHydrocarbonType: "Sweet Crude Oil (34.5° API, GOR 450 scf/bbl)",
        },
        offsetWells: [
          {
            wellId: "DJN-178",
            wellName: "DJN-178 (Primary Analogue)",
            distanceKm: 1.8,
            bearing: "NW (315°)",
            formationMatchPct: 92,
            trajectorySimilarityPct: 86,
            eventSimilarityPct: 88,
            overallScorePct: 91,
            recordedEventsCount: 4,
            keyHazardsRecorded: ["Severe Mud Loss (3,040 m)", "Torque drag spike (3,310 m)"],
            actualTd: 3480,
            operator: "Oil India Limited (OIL)",
            spudDate: "2019-04-12",
          },
          {
            wellId: "DJN-181",
            wellName: "DJN-181 (Offset Producer)",
            distanceKm: 3.1,
            bearing: "SW (220°)",
            formationMatchPct: 89,
            trajectorySimilarityPct: 81,
            eventSimilarityPct: 84,
            overallScorePct: 87,
            recordedEventsCount: 3,
            keyHazardsRecorded: ["Overpressure gas influx (2,910 m)", "Differential sticking (3,340 m)"],
            actualTd: 3550,
            operator: "Oil India Limited (OIL)",
            spudDate: "2020-08-05",
          },
          {
            wellId: "DJN-167",
            wellName: "DJN-167 (Up-dip Appraisal)",
            distanceKm: 4.2,
            bearing: "NE (040°)",
            formationMatchPct: 82,
            trajectorySimilarityPct: 78,
            eventSimilarityPct: 76,
            overallScorePct: 79,
            recordedEventsCount: 5,
            keyHazardsRecorded: ["Total mud loss in Disang vug", "Pack-off in Girujan clay"],
            actualTd: 3620,
            operator: "Oil India Limited (OIL)",
            spudDate: "2018-02-18",
          },
          {
            wellId: "DJN-162",
            wellName: "DJN-162 (Flank Delineation)",
            distanceKm: 5.6,
            bearing: "SE (135°)",
            formationMatchPct: 76,
            trajectorySimilarityPct: 70,
            eventSimilarityPct: 72,
            overallScorePct: 73,
            recordedEventsCount: 2,
            keyHazardsRecorded: ["Minor loss in Tipam upper sand"],
            actualTd: 3410,
            operator: "Oil India Limited (OIL)",
            spudDate: "2017-11-20",
          },
          {
            wellId: "DJN-149",
            wellName: "DJN-149 (Basin Margin)",
            distanceKm: 6.3,
            bearing: "South (180°)",
            formationMatchPct: 71,
            trajectorySimilarityPct: 66,
            eventSimilarityPct: 69,
            overallScorePct: 69,
            recordedEventsCount: 1,
            keyHazardsRecorded: ["Shale swelling in Girujan"],
            actualTd: 3380,
            operator: "Oil India Limited (OIL)",
            spudDate: "2016-06-14",
          },
        ],
        formationForecast: [
          {
            formation: "Alluvium / Post-Dihing",
            topMd: 0,
            baseMd: 500,
            lithology: "Unconsolidated sands, gravels, clay",
            mudLossProb: 5,
            stuckPipeProb: 3,
            kickProb: 1,
            overpressureProb: 2,
            riskRating: "LOW",
            recMudWeightSG: "1.04 - 1.08",
            historicalIncidents: "Normal hydrostatic gradient. Minimal hazard.",
          },
          {
            formation: "Tipam Sandstone",
            topMd: 500,
            baseMd: 2200,
            lithology: "Coarse-to-medium sandstone with intercalated silt",
            mudLossProb: 28,
            stuckPipeProb: 18,
            kickProb: 5,
            overpressureProb: 24,
            riskRating: "LOW",
            recMudWeightSG: "1.10 - 1.15",
            historicalIncidents: "High ROP section. Permeable thief sands observed at 1,450 m.",
          },
          {
            formation: "Girujan Clay",
            topMd: 2200,
            baseMd: 2800,
            lithology: "Variegated smectite-rich reactive shale",
            mudLossProb: 42,
            stuckPipeProb: 36,
            kickProb: 12,
            overpressureProb: 38,
            riskRating: "MEDIUM",
            recMudWeightSG: "1.15 - 1.18",
            historicalIncidents: "Reactive swelling and borehole narrowing noted in DJN-167.",
          },
          {
            formation: "Disang Formation (Target)",
            topMd: 2800,
            baseMd: 3300,
            lithology: "Hard splintery dark shale with hydrocarbon sands",
            mudLossProb: 68,
            stuckPipeProb: 54,
            kickProb: 22,
            overpressureProb: 61,
            riskRating: "HIGH",
            recMudWeightSG: "1.20 - 1.24",
            historicalIncidents: "Severe mud loss (72%) at 3,020-3,180 m across 6 offset wells.",
          },
          {
            formation: "Barail Shale & Arenaceous",
            topMd: 3300,
            baseMd: 3500,
            lithology: "Tight sandstone, carbonaceous shale, coal bands",
            mudLossProb: 31,
            stuckPipeProb: 28,
            kickProb: 14,
            overpressureProb: 36,
            riskRating: "MEDIUM",
            recMudWeightSG: "1.22 - 1.25",
            historicalIncidents: "Torque spikes and differential sticking on coal streaks.",
          },
          {
            formation: "Basement Complex",
            topMd: 3500,
            baseMd: 3750,
            lithology: "Granitic gneiss / Metamorphics",
            mudLossProb: 12,
            stuckPipeProb: 9,
            kickProb: 3,
            overpressureProb: 8,
            riskRating: "LOW",
            recMudWeightSG: "1.18 - 1.22",
            historicalIncidents: "Abrasive hard drilling with low ROP.",
          },
        ],
        keyRiskZones: [
          {
            depthRange: "2,850 - 2,950 m",
            formation: "Disang Fm. Transition",
            primaryRisk: "Abrupt Overpressure Ramp (1.24 SG Eq.)",
            probabilityPct: 61,
            severity: "HIGH",
            nearbyEvidence: "4 offset wells (2 documented gas influx kicks)",
            offsetWellCorrelation: "DJN-181 registered 1.24 SG pore pressure surge at 2,910 m.",
          },
          {
            depthRange: "3,020 - 3,180 m",
            formation: "Disang Fm. Fracture Horizon",
            primaryRisk: "Severe Lost Circulation / Mud Loss",
            probabilityPct: 72,
            severity: "CRITICAL",
            nearbyEvidence: "6 offset wells (3 major loss events, avg 85 m³ lost)",
            offsetWellCorrelation: "DJN-178 lost 92 m³ at 3,040 m; required LCM pill + squeeze.",
          },
          {
            depthRange: "3,320 - 3,380 m",
            formation: "Barail Shale & Coal Stringers",
            primaryRisk: "Differential Mechanical Pipe Sticking",
            probabilityPct: 54,
            severity: "HIGH",
            nearbyEvidence: "3 offset wells (2 differential sticking incidents)",
            offsetWellCorrelation: "DJN-181 experienced 14.5 hrs NPT jarring free at 3,340 m.",
          },
          {
            depthRange: "3,420 - 3,480 m",
            formation: "Barail Lower Arenaceous",
            primaryRisk: "Severe Torque Spike & Bit Bounce",
            probabilityPct: 45,
            severity: "MEDIUM",
            nearbyEvidence: "3 offset wells (1 cutter damage event)",
            offsetWellCorrelation: "DJN-178 recorded 48 kN·m peak torque necessitating bit pull.",
          },
        ],
        scenarios: [
          {
            id: "scenario-a",
            name: "Scenario A",
            label: "Baseline Mud Weight (1.15 SG)",
            kopMd: 1800,
            targetInclinationDeg: 25,
            azimuthDeg: 120,
            mudWeightSG: 1.15,
            estDrillingDays: 32.5,
            estNptDays: 7.8,
            avgRopMhr: 12.4,
            mudLossRiskPct: 72,
            stuckPipeRiskPct: 36,
            kickRiskPct: 22,
            overallRisk: "HIGH",
            description:
              "Standard historical mud weight. Lower drilling cost initially, but high exposure to overpressure influx in Disang and severe mud loss.",
            keyMitigations: [
              "Maintain high standby mud volume on surface (min 150 m³)",
              "Rig up continuous trip tank monitoring",
            ],
          },
          {
            id: "scenario-b",
            name: "Scenario B",
            label: "Higher Mud Weight (1.22 SG)",
            kopMd: 1800,
            targetInclinationDeg: 25,
            azimuthDeg: 120,
            mudWeightSG: 1.22,
            estDrillingDays: 34.1,
            estNptDays: 5.2,
            avgRopMhr: 11.2,
            mudLossRiskPct: 41,
            stuckPipeRiskPct: 24,
            kickRiskPct: 8,
            overallRisk: "MEDIUM",
            description:
              "Elevates mud weight through 2,900-3,200 m to control pore pressure surge. Decreases kick and wellbore collapse risk but slightly reduces ROP.",
            keyMitigations: [
              "Pre-treat active system with medium-sized calcium carbonate LCM (25 ppb)",
              "Optimize hydraulics to keep ECD below 1.28 SG fracture threshold",
            ],
          },
          {
            id: "scenario-c",
            name: "Scenario C",
            label: "Optimized Trajectory & Managed Mud Weight (Recommended)",
            kopMd: 2000,
            targetInclinationDeg: 21,
            azimuthDeg: 115,
            mudWeightSG: 1.18,
            estDrillingDays: 29.8,
            estNptDays: 4.6,
            avgRopMhr: 13.8,
            mudLossRiskPct: 38,
            stuckPipeRiskPct: 21,
            kickRiskPct: 6,
            overallRisk: "MEDIUM",
            description:
              "Recommended optimal engineering plan. Deeper KOP (2,000 m) lowers build rate doglegs, keeps inclination gentler (21°), avoids fault strike intersection, and manages ECD tightly.",
            keyMitigations: [
              "Deeper KOP at 2,000 m reduces drag by 28% through upper formations",
              "Dynamic mud weight stepping: 1.12 SG (surface-2,200m) -> 1.18 SG (2,200-2,800m) -> 1.22 SG (2,800-3,300m)",
              "Engineered 40-bbl coarse fiber LCM pill spotted on bottom before entering 3,020 m horizon",
            ],
          },
        ],
        drillingRecommendations: {
          generalSummary:
            "The planned well DJN-301 intersects oil-bearing Tipam and Disang reservoirs. Historical offset drilling across DJN-178, 181, and 167 highlights that rigorous mud weight scheduling, high-performance water-based mud (HPWBM), and pre-emptive LCM placement eliminate 85% of documented offset NPT.",
          steps: [
            {
              interval: "Phase 1: Surface Conductor & Spud (0 - 500 m)",
              depthRange: "0 - 500 m MD",
              formation: "Alluvium / Dihing",
              operationalGuideline:
                "Drill vertical with 17-1/2\" bit and spud mud (gel-bentonite). Set 13-3/8\" conductor at 500 m in competent clay bed to seal shallow aquifers.",
              mudWeightAndRheology: "Mud Weight: 1.04 - 1.08 SG, Viscosity: 45 - 55 s/qt, PV: 12 cP, YP: 18 lb/100ft²",
              bhaAndBitType: "17-1/2\" Roller Cone / IADC 117 or 5-blade PDC with shock sub",
              hydraulicsAndRpm: "Flow: 3,200 - 3,600 L/min, WOB: 60 - 90 kN, RPM: 110 - 130 rpm",
              hazardPrecaution: "Watch for gravel washouts; pump high-vis sweeps every 60 m.",
            },
            {
              interval: "Phase 2: Intermediate Fast Drilling (500 - 2,200 m)",
              depthRange: "500 - 2,200 m MD",
              formation: "Tipam Sandstone",
              operationalGuideline:
                "Drill with 12-1/4\" bit. Maintain smooth ROP. Initiate kick-off point (KOP) at 2,000 m with steerable RSS/motor to build angle at 2.5°/30m up to 21° inclination along 115° azimuth.",
              mudWeightAndRheology: "Mud Weight: 1.10 - 1.14 SG, Filtrate API Loss < 6 ml/30min",
              bhaAndBitType: "12-1/4\" 6-blade PDC (Matrix body, 16mm cutters) + 8\" Mud Motor (1.5° bend) / RSS",
              hydraulicsAndRpm: "Flow: 2,600 - 3,000 L/min, WOB: 80 - 120 kN, RPM: 80 motor + 50 string",
              hazardPrecaution: "Monitor standpipe pressure for thief sand dynamic loss at 1,450 m.",
            },
            {
              interval: "Phase 3: Reactive Clay Stabilization (2,200 - 2,800 m)",
              depthRange: "2,200 - 2,800 m MD",
              formation: "Girujan Clay Barrier",
              operationalGuideline:
                "Transition to High-Performance Inhibitive Glycol/Polymer Mud to prevent shale hydration and dispersion. Set 9-5/8\" casing shoe at 2,780 m.",
              mudWeightAndRheology: "Mud Weight: 1.16 - 1.18 SG, Glycol concentration 4.5% v/v, K+ ion > 30,000 ppm",
              bhaAndBitType: "12-1/4\" PDC with cutter depth-of-cut control (DOCC) to prevent bit-whirl",
              hydraulicsAndRpm: "Flow: 2,400 - 2,800 L/min, WOB: 70 - 100 kN, RPM: 100 rpm",
              hazardPrecaution: "Perform wiper trip every 250 m; monitor hole backreaming torque.",
            },
            {
              interval: "Phase 4: High-Risk Reservoir Penetration (2,800 - 3,300 m)",
              depthRange: "2,800 - 3,300 m MD",
              formation: "Disang Formation (Target Horizon)",
              operationalGuideline:
                "Drill 8-1/2\" hole. Raise mud weight to 1.22 SG prior to 2,850 m overpressure entry. Rig up continuous PWD (pressure-while-drilling) tool to maintain ECD < 1.27 SG.",
              mudWeightAndRheology: "Mud Weight: 1.22 SG, Low solid non-damaging polymer, HPHT fluid loss < 10 ml",
              bhaAndBitType: "8-1/2\" Premium PDC (13mm hybrid impregnated cutters) + Rotary Steerable System (RSS) + PWD + LWD",
              hydraulicsAndRpm: "Flow: 1,600 - 1,900 L/min, WOB: 50 - 80 kN, RPM: 120 - 140 rpm",
              hazardPrecaution:
                "Pre-treat active system with 30 ppb dual-particle LCM prior to 3,020 m. If dynamic losses occur > 5 m³/h, spot 40-bbl cross-linked pill immediately.",
            },
            {
              interval: "Phase 5: Target TD Completion (3,300 - 3,500 m)",
              depthRange: "3,300 - 3,500 m MD",
              formation: "Barail Shale & Target Pay",
              operationalGuideline:
                "Drill to final target TD (3,500 m MD / 3,320 m TVD). Log with triple-combo LWD. Circulate hole clean at 1.5x bottoms-up, pull out on elevators without swabbing. Run 7\" production liner.",
              mudWeightAndRheology: "Mud Weight: 1.22 - 1.24 SG, Lubricant 2.5% to minimize coal streak drag",
              bhaAndBitType: "8-1/2\" PDC with gauge pads + LWD Resistivity/Neutron-Density + Sonic",
              hydraulicsAndRpm: "Flow: 1,500 - 1,750 L/min, WOB: 40 - 70 kN, RPM: 110 rpm",
              hazardPrecaution: "Maintain continuous pipe rotation while reciprocating to prevent differential sticking.",
            },
          ],
          ecdTorqueMitigation:
            "Offset well DJN-178 exhibited severe torque escalation (+38%) at 3,310 m due to coal stringer friction. Adding 2.5% ester-based lubricant and maintaining flow rate above 1,700 L/min reduces ECD peaks by 0.04 SG and mitigates friction coefficients by 35%.",
          lcmPillStrategy:
            "Engineered fiber pill formulation: 20 ppb medium walnut shell, 15 ppb coarse calcium carbonate, 5 ppb cellulosic fibers. Have 50 m³ pill mixed in pill pit ready before breaking into the 3,020 m Disang loss horizon.",
          casingProgram: [
            { section: "Surface Conductor", holeSize: "17-1/2\"", casingSize: "13-3/8\" 54.5# J-55", shoeDepth: "500 m MD" },
            { section: "Intermediate Casing", holeSize: "12-1/4\"", casingSize: "9-5/8\" 40.0# N-80", shoeDepth: "2,780 m MD" },
            { section: "Production Liner", holeSize: "8-1/2\"", casingSize: "7\" 29.0# P-110", shoeDepth: "3,500 m MD (TOL @ 2,650 m)" },
          ],
        },
        aiRecommendationSummary:
          "Scenario C delivers the optimal trade-off between drilling cycle time (29.8 days vs 34.1 days baseline) and operational safety (mud loss probability lowered from 72% to 38%). Setting intermediate casing shoe in Girujan Clay (2,780 m) before transitioning to 1.22 SG mud through the overpressured Disang zone eliminates kick vulnerability while avoiding excessive hydrostatic fracturing.",
      },
      {
        id: "DJN-302",
        name: "DJN-302 (North Step-out)",
        code: "DJN-302",
        field: "Duliajan Field",
        basin: "Upper Assam Basin",
        targetFormation: "Barail Sandstone & Kopili Fm",
        wellType: "Exploration",
        targetTdMd: 3850,
        targetTvd: 3680,
        surfaceLat: 27.368,
        surfaceLng: 95.346,
        surfaceUtmX: 435400,
        surfaceUtmY: 3027700,
        crs: "WGS 84 / UTM Zone 46N (EPSG:32646)",
        searchRadiusKm: 10,
        geologicalJustification: {
          targetStructure: "North Fault Down-thrown Roll-over Anticline",
          structuralClosure: "310 m vertical closure with hydrocarbon column thickness 28 m",
          faultSealingIntegrity: "Moderate-High (Gouge ratio 0.65). Requires 200 m standoff from shear plane.",
          reservoirQualityIndex: "0.79 (Estimated net pay: 26.5 m)",
          permeabilityPorosityEst: "Porosity: 17.0% - 21.0%, Permeability: 90 - 240 mD",
          scientificRationale:
            "Tests untested structural trap along the northern step-out boundary. Seismic amplitude anomaly indicates presence of gas cap in Upper Barail with strong acoustic impedance contrast.",
          expectedHydrocarbonType: "Gas-Condensate with light oil rim (42.0° API)",
        },
        offsetWells: [
          {
            wellId: "DJN-167",
            wellName: "DJN-167 (Closest Step-out)",
            distanceKm: 2.1,
            bearing: "West (260°)",
            formationMatchPct: 94,
            trajectorySimilarityPct: 82,
            eventSimilarityPct: 85,
            overallScorePct: 89,
            recordedEventsCount: 5,
            keyHazardsRecorded: ["Total mud loss in Disang vug (2,890 m)", "Gas kick in Barail (3,410 m)"],
            actualTd: 3620,
            operator: "Oil India Limited (OIL)",
            spudDate: "2018-02-18",
          },
          {
            wellId: "DJN-178",
            wellName: "DJN-178 (Reference Stratigraphy)",
            distanceKm: 4.8,
            bearing: "SW (215°)",
            formationMatchPct: 81,
            trajectorySimilarityPct: 75,
            eventSimilarityPct: 79,
            overallScorePct: 79,
            recordedEventsCount: 4,
            keyHazardsRecorded: ["Severe Mud Loss (3,040 m)"],
            actualTd: 3480,
            operator: "Oil India Limited (OIL)",
            spudDate: "2019-04-12",
          },
          {
            wellId: "DJN-181",
            wellName: "DJN-181 (Field Southern Anchor)",
            distanceKm: 6.2,
            bearing: "SSW (205°)",
            formationMatchPct: 73,
            trajectorySimilarityPct: 68,
            eventSimilarityPct: 71,
            overallScorePct: 71,
            recordedEventsCount: 3,
            keyHazardsRecorded: ["Overpressure gas influx (2,910 m)"],
            actualTd: 3550,
            operator: "Oil India Limited (OIL)",
            spudDate: "2020-08-05",
          },
        ],
        formationForecast: [
          {
            formation: "Alluvium",
            topMd: 0,
            baseMd: 480,
            lithology: "Sands, gravels, surface clay",
            mudLossProb: 4,
            stuckPipeProb: 2,
            kickProb: 1,
            overpressureProb: 1,
            riskRating: "LOW",
            recMudWeightSG: "1.05 - 1.08",
            historicalIncidents: "Normal hydrostatic gradient.",
          },
          {
            formation: "Tipam Sandstone",
            topMd: 480,
            baseMd: 2350,
            lithology: "Massive porous sandstone",
            mudLossProb: 32,
            stuckPipeProb: 15,
            kickProb: 4,
            overpressureProb: 18,
            riskRating: "LOW",
            recMudWeightSG: "1.10 - 1.15",
            historicalIncidents: "Thief zones between 1,200 - 1,600 m.",
          },
          {
            formation: "Girujan Clay",
            topMd: 2350,
            baseMd: 2950,
            lithology: "Montmorillonite rich swelling claystone",
            mudLossProb: 38,
            stuckPipeProb: 48,
            kickProb: 15,
            overpressureProb: 44,
            riskRating: "HIGH",
            recMudWeightSG: "1.18 - 1.22",
            historicalIncidents: "Thickened interval near North Fault; requires heavy chemical inhibition.",
          },
          {
            formation: "Disang Formation",
            topMd: 2950,
            baseMd: 3450,
            lithology: "Hard fractured shale & tight siltstone",
            mudLossProb: 74,
            stuckPipeProb: 51,
            kickProb: 34,
            overpressureProb: 68,
            riskRating: "CRITICAL",
            recMudWeightSG: "1.24 - 1.28",
            historicalIncidents: "Severe fault drag and high pressure gas bubble.",
          },
          {
            formation: "Barail Sandstone (Target)",
            topMd: 3450,
            baseMd: 3850,
            lithology: "Fine-grained gas sandstone & coal bands",
            mudLossProb: 25,
            stuckPipeProb: 30,
            kickProb: 28,
            overpressureProb: 45,
            riskRating: "MEDIUM",
            recMudWeightSG: "1.25 - 1.29",
            historicalIncidents: "Gas kick potential upon entering virgin pressure reservoir.",
          },
        ],
        keyRiskZones: [
          {
            depthRange: "2,980 - 3,120 m",
            formation: "Disang North Fault Shear",
            primaryRisk: "Catastrophic Mud Loss & Influx Coupling",
            probabilityPct: 78,
            severity: "CRITICAL",
            nearbyEvidence: "DJN-167 recorded 120 m³ fluid drop in 40 mins",
            offsetWellCorrelation: "High proximity to North Fault zone creates open tension fractures.",
          },
          {
            depthRange: "3,450 - 3,520 m",
            formation: "Upper Barail Gas Cap Entry",
            primaryRisk: "High-Pressure Gas Influx (Kick)",
            probabilityPct: 64,
            severity: "HIGH",
            nearbyEvidence: "DJN-167 took 18 bbl gas kick requiring kill sheet circulation",
            offsetWellCorrelation: "Pore pressure rises rapidly from 1.19 to 1.27 SG equivalent.",
          },
        ],
        scenarios: [
          {
            id: "scenario-a",
            name: "Scenario A",
            label: "Conventional Heavy Mud (1.24 SG)",
            kopMd: 1900,
            targetInclinationDeg: 28,
            azimuthDeg: 35,
            mudWeightSG: 1.24,
            estDrillingDays: 38.5,
            estNptDays: 9.4,
            avgRopMhr: 9.8,
            mudLossRiskPct: 68,
            stuckPipeRiskPct: 44,
            kickRiskPct: 18,
            overallRisk: "HIGH",
            description: "High hydrostatic column to counter gas influx but causes fracture breakdown.",
            keyMitigations: ["Standby heavy barite weighting material (100 MT)"],
          },
          {
            id: "scenario-b",
            name: "Scenario B",
            label: "Managed Pressure Drilling (MPD) + Synthetic Mud (Recommended)",
            kopMd: 2200,
            targetInclinationDeg: 22,
            azimuthDeg: 40,
            mudWeightSG: 1.20,
            estDrillingDays: 31.0,
            estNptDays: 3.8,
            avgRopMhr: 13.5,
            mudLossRiskPct: 29,
            stuckPipeRiskPct: 18,
            kickRiskPct: 5,
            overallRisk: "LOW",
            description:
              "MPD with automated choke back-pressure allows precise bottom-hole pressure control between 1.20 and 1.26 SG, preventing both kicks and dynamic fracture losses.",
            keyMitigations: [
              "Deploy MPD closed-loop surface system with Coriolis flow meter",
              "Synthetic-based mud (SBM) 80/20 oil-water ratio for shale stability",
            ],
          },
        ],
        drillingRecommendations: {
          generalSummary:
            "DJN-302 step-out exploration targets deeper Barail horizons near the North Fault. Utilizing MPD closed-loop pressure management is strongly recommended to navigate the narrow drilling window between pore pressure (1.23 SG) and fracture gradient (1.29 SG).",
          steps: [
            {
              interval: "Phase 1: Conductor Hole (0 - 480 m)",
              depthRange: "0 - 480 m MD",
              formation: "Alluvium",
              operationalGuideline: "Spud with 17-1/2\" bit. Set 13-3/8\" casing at 480 m.",
              mudWeightAndRheology: "Mud Weight: 1.06 SG",
              bhaAndBitType: "17-1/2\" TCI Tricone",
              hydraulicsAndRpm: "Flow: 3,400 L/min, WOB: 70 kN, RPM: 120 rpm",
              hazardPrecaution: "Isolate surficial loose alluvial sands.",
            },
            {
              interval: "Phase 2: Upper Trajectory Section (480 - 2,350 m)",
              depthRange: "480 - 2,350 m MD",
              formation: "Tipam Sandstone",
              operationalGuideline: "Drill 12-1/4\" hole. Initiate KOP at 2,200 m.",
              mudWeightAndRheology: "Mud Weight: 1.12 SG, Polymer WBM",
              bhaAndBitType: "12-1/4\" 5-blade PDC with RSS",
              hydraulicsAndRpm: "Flow: 2,800 L/min, WOB: 90 kN, RPM: 130 rpm",
              hazardPrecaution: "Monitor standpipe pressure across thief zones.",
            },
            {
              interval: "Phase 3: Fault Buffer & Girujan (2,350 - 2,950 m)",
              depthRange: "2,350 - 2,950 m MD",
              formation: "Girujan Clay",
              operationalGuideline: "Switch to Synthetic Based Mud. Set 9-5/8\" casing shoe at 2,920 m.",
              mudWeightAndRheology: "Mud Weight: 1.20 SG, SBM 80/20",
              bhaAndBitType: "12-1/4\" PDC with vibration damping sub",
              hydraulicsAndRpm: "Flow: 2,400 L/min, WOB: 85 kN, RPM: 100 rpm",
              hazardPrecaution: "Run 9-5/8\" casing promptly to avoid extended open-hole exposure.",
            },
            {
              interval: "Phase 4: MPD Reservoir Section (2,950 - 3,850 m)",
              depthRange: "2,950 - 3,850 m MD",
              formation: "Disang & Barail Sandstone",
              operationalGuideline: "Drill 8-1/2\" hole using MPD system with 200 psi surface backpressure.",
              mudWeightAndRheology: "Mud Weight: 1.20 SG base (1.25 SG effective with SBP)",
              bhaAndBitType: "8-1/2\" Matrix PDC + RSS + LWD Triple Combo + Fast Gamma",
              hydraulicsAndRpm: "Flow: 1,750 L/min, WOB: 65 kN, RPM: 140 rpm",
              hazardPrecaution: "Real-time kick detection via automated Coriolis mass flow balance.",
            },
          ],
          ecdTorqueMitigation: "SBM reduces string torque by 40% compared to WBM in directional intervals.",
          lcmPillStrategy: "Calcium carbonate blend (50/150/400 micron) loaded continuously in active system.",
          casingProgram: [
            { section: "Conductor", holeSize: "17-1/2\"", casingSize: "13-3/8\" 54.5#", shoeDepth: "480 m MD" },
            { section: "Intermediate", holeSize: "12-1/4\"", casingSize: "9-5/8\" 47.0# L-80", shoeDepth: "2,920 m MD" },
            { section: "Production", holeSize: "8-1/2\"", casingSize: "7\" 29.0# P-110", shoeDepth: "3,850 m MD" },
          ],
        },
        aiRecommendationSummary:
          "Scenario B (MPD + Synthetic Mud) is strongly recommended for DJN-302. Closed-loop pressure control eliminates the risk of kick-loss crossflow in the narrow 0.06 SG window near the North Fault, saving an estimated 7.5 days in drilling cycle time.",
      },
      {
        id: "DJN-303",
        name: "DJN-303 (Fault Flank Appraisal)",
        code: "DJN-303",
        field: "Duliajan Field",
        basin: "Upper Assam Basin",
        targetFormation: "Disang Formation Mid-Sands",
        wellType: "Appraisal",
        targetTdMd: 3420,
        targetTvd: 3260,
        surfaceLat: 27.325,
        surfaceLng: 95.308,
        surfaceUtmX: 431600,
        surfaceUtmY: 3022900,
        crs: "WGS 84 / UTM Zone 46N (EPSG:32646)",
        searchRadiusKm: 10,
        geologicalJustification: {
          targetStructure: "Southwest Flank Structural Nose",
          structuralClosure: "260 m structural relief against southern thrust barrier",
          faultSealingIntegrity: "High (Thrust fault gauge seal)",
          reservoirQualityIndex: "0.81 (Net pay: 31.0 m)",
          permeabilityPorosityEst: "Porosity: 18.5% - 22.0%, Permeability: 110 - 280 mD",
          scientificRationale:
            "Delineates the southwest boundary of the main producing pool. Offset well DJN-181 produced 420 bbl/d from equivalent sand; DJN-303 tests up-dip attic oil potential.",
          expectedHydrocarbonType: "Medium Crude Oil (33.0° API)",
        },
        offsetWells: [
          {
            wellId: "DJN-181",
            wellName: "DJN-181 (Direct Offset)",
            distanceKm: 1.5,
            bearing: "ENE (065°)",
            formationMatchPct: 96,
            trajectorySimilarityPct: 89,
            eventSimilarityPct: 91,
            overallScorePct: 94,
            recordedEventsCount: 3,
            keyHazardsRecorded: ["Overpressure gas influx (2,910 m)", "Differential sticking (3,340 m)"],
            actualTd: 3550,
            operator: "Oil India Limited (OIL)",
            spudDate: "2020-08-05",
          },
          {
            wellId: "DJN-178",
            wellName: "DJN-178 (North Offset)",
            distanceKm: 2.7,
            bearing: "NNE (025°)",
            formationMatchPct: 88,
            trajectorySimilarityPct: 84,
            eventSimilarityPct: 82,
            overallScorePct: 86,
            recordedEventsCount: 4,
            keyHazardsRecorded: ["Severe Mud Loss (3,040 m)"],
            actualTd: 3480,
            operator: "Oil India Limited (OIL)",
            spudDate: "2019-04-12",
          },
        ],
        formationForecast: [
          {
            formation: "Alluvium",
            topMd: 0,
            baseMd: 510,
            lithology: "Sands, clay",
            mudLossProb: 4,
            stuckPipeProb: 2,
            kickProb: 1,
            overpressureProb: 1,
            riskRating: "LOW",
            recMudWeightSG: "1.05 - 1.08",
            historicalIncidents: "Normal hydrostatic.",
          },
          {
            formation: "Tipam Sandstone",
            topMd: 510,
            baseMd: 2180,
            lithology: "Sandstone",
            mudLossProb: 24,
            stuckPipeProb: 14,
            kickProb: 4,
            overpressureProb: 20,
            riskRating: "LOW",
            recMudWeightSG: "1.10 - 1.15",
            historicalIncidents: "Steady drilling.",
          },
          {
            formation: "Girujan Clay",
            topMd: 2180,
            baseMd: 2750,
            lithology: "Claystone",
            mudLossProb: 35,
            stuckPipeProb: 32,
            kickProb: 10,
            overpressureProb: 32,
            riskRating: "MEDIUM",
            recMudWeightSG: "1.15 - 1.18",
            historicalIncidents: "Minor sloughing.",
          },
          {
            formation: "Disang Formation (Target)",
            topMd: 2750,
            baseMd: 3420,
            lithology: "Sandstone / Shale intercalations",
            mudLossProb: 52,
            stuckPipeProb: 40,
            kickProb: 18,
            overpressureProb: 50,
            riskRating: "HIGH",
            recMudWeightSG: "1.21 - 1.23",
            historicalIncidents: "Overpressure influx at 2,900 m.",
          },
        ],
        keyRiskZones: [
          {
            depthRange: "2,870 - 2,960 m",
            formation: "Disang Transition",
            primaryRisk: "Overpressure Influx",
            probabilityPct: 56,
            severity: "HIGH",
            nearbyEvidence: "DJN-181 gas influx registered at 2,910 m",
            offsetWellCorrelation: "Pore pressure ramp to 1.23 SG.",
          },
        ],
        scenarios: [
          {
            id: "scenario-a",
            name: "Scenario A",
            label: "Standard Infill Plan (Recommended)",
            kopMd: 1750,
            targetInclinationDeg: 19,
            azimuthDeg: 210,
            mudWeightSG: 1.20,
            estDrillingDays: 27.2,
            estNptDays: 3.4,
            avgRopMhr: 14.2,
            mudLossRiskPct: 34,
            stuckPipeRiskPct: 18,
            kickRiskPct: 5,
            overallRisk: "LOW",
            description: "Straightforward directional appraisal trajectory with gentle build rate.",
            keyMitigations: ["Pre-treat mud weight to 1.20 SG prior to 2,800 m"],
          },
        ],
        drillingRecommendations: {
          generalSummary: "DJN-303 appraisal well offers clean reservoir exposure with low trajectory complexity.",
          steps: [
            {
              interval: "Phase 1: Spud (0 - 510 m)",
              depthRange: "0 - 510 m MD",
              formation: "Alluvium",
              operationalGuideline: "Drill vertical. Casing 13-3/8\" at 510 m.",
              mudWeightAndRheology: "1.06 SG",
              bhaAndBitType: "17-1/2\" Tricone",
              hydraulicsAndRpm: "3,300 L/min, 75 kN, 120 rpm",
              hazardPrecaution: "Isolate freshwater zone.",
            },
            {
              interval: "Phase 2: Target Section (510 - 3,420 m)",
              depthRange: "510 - 3,420 m MD",
              formation: "Tipam / Girujan / Disang",
              operationalGuideline: "Build angle to 19° at KOP 1,750 m. Set 9-5/8\" casing at 2,740 m.",
              mudWeightAndRheology: "1.15 -> 1.21 SG",
              bhaAndBitType: "8-1/2\" PDC + Motor",
              hydraulicsAndRpm: "1,800 L/min, 70 kN, 130 rpm",
              hazardPrecaution: "Watch pore pressure ramp at 2,870 m.",
            },
          ],
          ecdTorqueMitigation: "Maintain laminar annular velocity to minimize ECD surges.",
          lcmPillStrategy: "Standard 30 bbl calcium carbonate pill on standby.",
          casingProgram: [
            { section: "Surface", holeSize: "17-1/2\"", casingSize: "13-3/8\"", shoeDepth: "510 m MD" },
            { section: "Intermediate", holeSize: "12-1/4\"", casingSize: "9-5/8\"", shoeDepth: "2,740 m MD" },
            { section: "Production", holeSize: "8-1/2\"", casingSize: "7\"", shoeDepth: "3,420 m MD" },
          ],
        },
        aiRecommendationSummary:
          "DJN-303 is an optimal low-risk appraisal location with 94% analogue fidelity to DJN-181. Standard mud weight progression of 1.20-1.21 SG ensures fast drilling (27.2 days) with low hazard probability.",
      },
    ],
  },
  {
    id: "forge-geothermal",
    name: "FORGE Geothermal Field (Milford, Utah)",
    basin: "Basin and Range Geothermal Province",
    centerLat: 38.504,
    centerLng: -112.903,
    defaultRadiusKm: 5,
    faultLines: [
      {
        name: "Opal Mound Fault (Hydrothermal Boundary)",
        type: "Normal Quaternary Fault",
        coords: [
          { lat: 38.52, lng: -112.92 },
          { lat: 38.505, lng: -112.905 },
          { lat: 38.485, lng: -112.89 },
        ],
      },
    ],
    highRiskZones: [
      {
        name: "Granite Transition High-Torque Hard Rock",
        riskType: "Extreme Temperature (230°C) & Bit Wear",
        centerLat: 38.504,
        centerLng: -112.903,
        radiusKm: 1.5,
      },
    ],
    potentialWells: [
      {
        id: "FORGE-16C",
        name: "FORGE 16C(78)-32 (Planned EGS Production Well)",
        code: "FORGE-16C",
        field: "FORGE Geothermal Area",
        basin: "Basin and Range",
        targetFormation: "Precambrian / Tertiary Granitic Gneiss",
        wellType: "Development",
        targetTdMd: 3400,
        targetTvd: 2650,
        surfaceLat: 38.504,
        surfaceLng: -112.903,
        surfaceUtmX: 334500,
        surfaceUtmY: 4263700,
        crs: "NAD83 / UTM Zone 12N (EPSG:26912)",
        searchRadiusKm: 5,
        geologicalJustification: {
          targetStructure: "Deep Enhanced Geothermal Reservoir in Crystalline Granite",
          structuralClosure: "Impermeable crystalline basement block with natural fracture matrix",
          faultSealingIntegrity: "Aseismic boundary 400m west of Opal Mound fault",
          reservoirQualityIndex: "0.91 (Target rock temperature: 228°C at 2,600 m TVD)",
          permeabilityPorosityEst: "Matrix Porosity: < 1.5%, Natural Fracture Permeability: 0.1 - 5.0 mD",
          scientificRationale:
            "Planned parallel producer well to existing injector FORGE 16B(78)-32 (offset 100 m). Trajectory parallels 16B along 65° inclination to create a commercial doublet for closed-loop geothermal heat extraction.",
          expectedHydrocarbonType: "Superheated Geothermal Brine (228°C)",
        },
        offsetWells: [
          {
            wellId: "16B(78)-32",
            wellName: "FORGE 16B(78)-32 (Direct Injector Doublet)",
            distanceKm: 0.12,
            bearing: "SE (120°)",
            formationMatchPct: 99,
            trajectorySimilarityPct: 95,
            eventSimilarityPct: 93,
            overallScorePct: 96,
            recordedEventsCount: 44,
            keyHazardsRecorded: ["Hard granite bit wear", "Mud thermal degradation at 225°C"],
            actualTd: 3340,
            operator: "University of Utah EGI",
            spudDate: "2021-04-10",
          },
        ],
        formationForecast: [
          {
            formation: "Alluvium / Quaternary Sediments",
            topMd: 0,
            baseMd: 960,
            lithology: "Alluvial gravels, rhyolite tuffs, volcanics",
            mudLossProb: 15,
            stuckPipeProb: 8,
            kickProb: 2,
            overpressureProb: 3,
            riskRating: "LOW",
            recMudWeightSG: "1.03 - 1.06",
            historicalIncidents: "Steady drilling.",
          },
          {
            formation: "Granitoid / Quartz Monzonite Basement",
            topMd: 960,
            baseMd: 3400,
            lithology: "Hard, abrasive granite & granodiorite (UCS > 240 MPa)",
            mudLossProb: 22,
            stuckPipeProb: 18,
            kickProb: 3,
            overpressureProb: 5,
            riskRating: "HIGH",
            recMudWeightSG: "1.04 - 1.08",
            historicalIncidents: "Extreme bit cutter abrasion; requires hybrid PDC/impregnated bits and mud cooling.",
          },
        ],
        keyRiskZones: [
          {
            depthRange: "960 - 1,050 m",
            formation: "Top Granite Interface",
            primaryRisk: "Severe Bit Bounce & Chatter",
            probabilityPct: 82,
            severity: "HIGH",
            nearbyEvidence: "16B experienced immediate ROP deceleration and cutter spalling",
            offsetWellCorrelation: "Lithology transition from soft volcanic tuff to 240 MPa granite.",
          },
          {
            depthRange: "2,400 - 3,400 m",
            formation: "Hot Granite Lateral",
            primaryRisk: "Thermal MWD Tool Failure (>200°C)",
            probabilityPct: 58,
            severity: "HIGH",
            nearbyEvidence: "16B required surface mud cooler chilling system",
            offsetWellCorrelation: "Bottomhole static temperature exceeds 228°C.",
          },
        ],
        scenarios: [
          {
            id: "scenario-a",
            name: "Scenario A",
            label: "Chilled Water Mud + Hybrid TCI/PDC (Recommended)",
            kopMd: 1600,
            targetInclinationDeg: 65,
            azimuthDeg: 105,
            mudWeightSG: 1.05,
            estDrillingDays: 24.5,
            estNptDays: 3.1,
            avgRopMhr: 8.5,
            mudLossRiskPct: 18,
            stuckPipeRiskPct: 12,
            kickRiskPct: 2,
            overallRisk: "LOW",
            description:
              "Utilizes surface evaporative mud chillers to maintain BHT < 70°C at surface, protected HT MWD tools, and high-durability diamond-enhanced inserts.",
            keyMitigations: [
              "Deploy dual-tower mud coolers to keep inlet temp < 45°C",
              "Use high-temp elastomer mud motors rated to 250°C",
            ],
          },
        ],
        drillingRecommendations: {
          generalSummary:
            "FORGE 16C(78)-32 planned geothermal doublet well requires high-temperature drilling practices honed during the FORGE 16B campaign. Surface mud chillers and specialized HT directional tools maintain drilling efficiency in 228°C crystalline granite.",
          steps: [
            {
              interval: "Phase 1: Sedimentary Overburden (0 - 960 m)",
              depthRange: "0 - 960 m MD",
              formation: "Alluvial & Volcanic Tuffs",
              operationalGuideline: "Drill 17-1/2\" vertical hole. Set 13-3/8\" surface casing at 960 m into top granite.",
              mudWeightAndRheology: "Mud Weight: 1.04 SG water-based gel",
              bhaAndBitType: "17-1/2\" TCI Roller Cone",
              hydraulicsAndRpm: "Flow: 3,500 L/min, WOB: 80 kN, RPM: 110 rpm",
              hazardPrecaution: "Isolate permeable basin sediments.",
            },
            {
              interval: "Phase 2: Granite KOP & Build Section (960 - 2,100 m)",
              depthRange: "960 - 2,100 m MD",
              formation: "Granitoid Basement",
              operationalGuideline:
                "Drill 12-1/4\" hole. Initiate directional kick-off at 1,600 m to build inclination to 65° along 105° azimuth.",
              mudWeightAndRheology: "Chilled water with polymer sweeps, Mud Weight: 1.05 SG",
              bhaAndBitType: "12-1/4\" Hybrid PDC/TCI with HT directional assembly",
              hydraulicsAndRpm: "Flow: 2,800 L/min, WOB: 110 kN, RPM: 70 motor + 40 string",
              hazardPrecaution: "Run surface mud chillers continuously to protect MWD electronics.",
            },
            {
              interval: "Phase 3: 65° Lateral Geothermal Reservoir (2,100 - 3,400 m)",
              depthRange: "2,100 - 3,400 m MD",
              formation: "Hot Granite Reservoir",
              operationalGuideline: "Drill 8-1/2\" tangent lateral at 65° inclination. Target TD at 3,400 m MD.",
              mudWeightAndRheology: "Chilled fresh water, high-temp lubricant",
              bhaAndBitType: "8-1/2\" Impregnated diamond bit + HT RSS",
              hydraulicsAndRpm: "Flow: 1,800 L/min, WOB: 90 kN, RPM: 130 rpm",
              hazardPrecaution: "Monitor vibration (stick-slip) in ultra-hard rock.",
            },
          ],
          ecdTorqueMitigation: "Circulate bottoms-up before each survey station to purge heavy granite cuttings.",
          lcmPillStrategy: "Geothermal-grade crosslinked polymer pills for natural fracture loss mitigation.",
          casingProgram: [
            { section: "Surface", holeSize: "17-1/2\"", casingSize: "13-3/8\" 68.0# L-80", shoeDepth: "960 m MD" },
            { section: "Intermediate", holeSize: "12-1/4\"", casingSize: "9-5/8\" 53.5# P-110", shoeDepth: "2,100 m MD" },
            { section: "Open Hole / Perforated Liner", holeSize: "8-1/2\"", casingSize: "7\" Liner", shoeDepth: "3,400 m MD" },
          ],
        },
        aiRecommendationSummary:
          "FORGE-16C leverages the verified 16B offset dataset to ensure seamless doublet execution. Maintaining continuous mud cooling and utilizing impregnated diamond cutting elements guarantees target reach with minimal NPT.",
      },
    ],
  },
];
